# Generated by Django 5.0.3 on 2024-04-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitoblar', '0003_kitob_user_alter_kitob_til'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='til',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='til', to='kitoblar.tillar'),
        ),
    ]
